name: Docker Compose Production

on:
  push:
    branches: [ 'main', 'master' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, prod]
    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
      SECRET: ${{ secrets.SECRET || secrets.secret }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Create Firebase Service Account File
        env:
          FIREBASE_SERVICE_ACCOUNT_FILE_CONTENT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FILE_CONTENT }}
        run: echo "$FIREBASE_SERVICE_ACCOUNT_FILE_CONTENT" > ./config/firebase-service-account.json
      
      - name: Run docker compose with prod profile
        run: |
          docker compose --profile prod up --build -d --remove-orphans
      
      - name: Show running containers
        run: |
          docker compose ps
